### ISSUE TITLE
Add ucode.proto to up-core-api source list

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-conan-recipes#9]
The UCode enumeration was pulled out of ustatus.proto and into its own file with https://github.com/eclipse-uprotocol/up-spec/pull/183

Recipes will fail to build until CMakeLists.txt for up-core-api is updated.

**Comment by BishrutSubedi** [comment]
PR for fix: https://github.com/eclipse-uprotocol/up-conan-recipes/pull/10
